'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class REGISTROANIME
    Public Property CODANIME As Integer
    Public Property NOMANIME As String
    Public Property TEMPORADAS As String
    Public Property DESCARGAR As String
    Public Property VISTO As String
    Public Property FOTO As Byte()

End Class
